const Products = [
  {
    id: 1,
    img: "img/Products/First_product.png",
    name: "product name",
    desc: "Product description on maybe 2 <br/> lines",
    heartIco: "img/Icons/cartWhite.png",
    favIco: "img/Icons/heartWhite.png",
    stars: "img/products/Stars.png",
    price: 100,
  },
  {
    id: 2,
    img: "img/Products/Sec_product.png",
    name: "product name",
    desc: "Product description on maybe 2 <br/> lines",
    heartIco: "img/Icons/cartWhite.png",
    favIco: "img/Icons/heartWhite.png",
    stars: "img/products/Stars.png",
    price: 300,
  },
  {
    id: 3,
    img: "img/Products/Third_product.png",
    name: "product name",
    desc: "Product description on maybe 2 <br/> lines",
    heartIco: "img/Icons/cartWhite.png",
    favIco: "img/Icons/heartWhite.png",
    stars: "img/products/Stars.png",
    price: 200,
  },
  {
    id: 4,
    img: "img/Products/Fourth_product.png",
    name: "product name",
    desc: "Product description on maybe 2 <br/> lines",
    heartIco: "img/Icons/cartWhite.png",
    favIco: "img/Icons/heartWhite.png",
    stars: "img/products/Stars.png",
    price: 400,
  },
];
